version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo}"]
      interval: 30s
      timeout: 10s
      retries: 3

  odoo:
    image: odoo:${ODOO_TAG:-18.0}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      HOST: db
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./oca:/mnt/oca-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - odoo-data:/var/lib/odoo
      - odoo-sessions:/var/lib/odoo/sessions
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["--"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      odoo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
  odoo-sessions:
    driver: local
