# docker-compose.local.yml - Odoo 18 + OCA + Local PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo-network

  odoo:
    image: odoo:18.0
    container_name: odoo18
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./oca:/mnt/oca:ro
      - ./config/odoo.local.conf:/etc/odoo/odoo.conf:ro
    networks:
      - odoo-network
    command: ["--dev=reload,xml"]

volumes:
  odoo-db-data:
  odoo-data:

networks:
  odoo-network:
    driver: bridge
