name: SuperClaude Orchestration Pipeline
version: 1.0.0
description: Agent-driven CI/CD with parallel execution

events:
  # PR Lifecycle
  - name: pr_opened
    trigger: github.pull_request.opened
    steps:
      - name: Create Odoo Task
        agent: odoo_integration
        with:
          action: create_task
          event: pr_opened

      - name: Parallel Code Review
        parallel:
          - agent: reviewer
            timeout: 300

          - agent: security-scan
            timeout: 180

          - agent: test-runner
            timeout: 600

      - name: Aggregate Results
        agent: superclaude
        with:
          task: aggregate_pr_results
          inputs: [reviewer, security-scan, test-runner]

      - name: Update Odoo
        agent: odoo_integration
        with:
          action: update_task
          event: ci_complete
          status: ${aggregate.status}

      - name: Post PR Comment
        if: aggregate.status == 'fail'
        agent: github_integration
        with:
          action: comment
          body: ${aggregate.summary}

  - name: pr_synchronized
    trigger: github.pull_request.synchronize
    steps:
      - name: Update Odoo Task
        agent: odoo_integration
        with:
          action: update_task
          event: pr_sync

      - name: Re-run Checks
        include: pr_opened.steps[1:]  # Reuse from pr_opened

  # Deployment Events
  - name: deploy_staging
    trigger: github.push.branches.staging
    steps:
      - name: Pre-Deploy Backup
        agent: devops
        with:
          task: backup
          environment: staging

      - name: Deploy to Staging
        agent: devops
        with:
          task: deploy
          environment: staging
          strategy: rolling

      - name: Wait for Health
        agent: devops
        with:
          task: health_check
          timeout: 120

      - name: Parallel Post-Deploy Checks
        parallel:
          - agent: test-runner
            with:
              task: smoke
              environment: staging

          - agent: security-scan
            with:
              task: runtime_check
              environment: staging

          - agent: analyst
            with:
              task: baseline_metrics
              environment: staging

      - name: Update Odoo
        agent: odoo_integration
        with:
          action: update_task
          event: deploy_staging
          url: ${deploy.url}

  - name: deploy_production
    trigger: github.push.tags
    required_approvers: 2
    steps:
      - name: Pre-Deploy Snapshot
        agent: devops
        with:
          task: backup
          environment: production
          snapshot: true

      - name: Deploy to Production
        agent: devops
        with:
          task: deploy
          environment: production
          strategy: blue_green
          canary_percent: 10

      - name: Canary Health Check
        agent: devops
        with:
          task: health_check
          timeout: 300

      - name: Parallel Production Validation
        parallel:
          - agent: test-runner
            with:
              task: smoke
              environment: production

          - agent: security-scan
            with:
              task: runtime_check
              environment: production

      - name: Full Traffic Switch
        if: validation.status == 'pass'
        agent: devops
        with:
          task: switch_traffic
          canary_percent: 100

      - name: Update Odoo
        agent: odoo_integration
        with:
          action: update_task
          event: deploy_prod
          tag: ${github.ref}

      - name: Rollback on Failure
        if: validation.status == 'fail'
        agent: devops
        with:
          task: rollback
          snapshot: ${backup.snapshot_id}

  # Scheduled Events
  - name: nightly_ops
    trigger: cron
    schedule: "0 2 * * *"  # 2 AM daily
    steps:
      - name: Parallel Maintenance
        parallel:
          - agent: devops
            with:
              task: backup
              environment: production

          - agent: devops
            with:
              task: ssl_renew

          - agent: analyst
            with:
              task: daily_metrics

          - agent: reviewer
            with:
              task: spec_drift_check

      - name: Send Report
        agent: odoo_integration
        with:
          action: post_message
          channel: "#ci-updates"
          message: "🌙 Nightly ops complete: ${summary}"

error_handling:
  on_failure:
    - agent: odoo_integration
      with:
        action: update_task
        event: blocked
        reason: ${error.message}

    - agent: odoo_integration
      with:
        action: post_message
        channel: "#ci-updates"
        message: "🚨 Pipeline failed: ${error.summary}"

  retry:
    max_attempts: 2
    delay: 5  # seconds
    exponential_backoff: true

  rollback:
    enabled: true
    automatic: true
    notify: true

notifications:
  channels:
    - name: "#ci-updates"
      events: [all]
      format: html

    - name: "#alerts"
      events: [failure, blocked]
      format: html
      mention: "@devops"

monitoring:
  metrics:
    - deployment_frequency
    - mean_time_to_deploy
    - change_failure_rate
    - mean_time_to_recovery

  dashboards:
    - odoo_project_kanban
    - grafana_ci_cd

  alerts:
    - name: high_failure_rate
      condition: change_failure_rate > 15
      action: notify_team

    - name: slow_deploys
      condition: mean_time_to_deploy > 3600
      action: investigate
