version: "3.8"
services:
  ocr:
    image: registry.digitalocean.com/fin-workspace/ocr-service:prod
    container_name: ocr-service
    ports:
      - "127.0.0.1:8000:8000"  # BIND TO LOCALHOST ONLY (internal access)
    environment:
      UVICORN_WORKERS: "2"
      LOG_LEVEL: "info"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
