name: odoboo-ocr-service
region: sgp
services:
  - name: ocr-api
    dockerfile_path: services/ocr-service/Dockerfile
    source_dir: services/ocr-service
    github:
      repo: your-org/odoboo-workspace
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8000
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: MODEL_NAME
        value: PaddleOCR
      - key: MIN_CONFIDENCE
        value: "0.60"
      - key: GPU_ENABLED
        value: "false"
      - key: LOG_LEVEL
        value: INFO
