http:
  middlewares:
    rate-login:
      rateLimit:
        average: 20
        burst: 40

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src 'self'"
        permissionsPolicy: "camera=(), geolocation=()"

# Note: Router configuration moved to compose.yaml Docker labels
# Traefik file provider does not expand environment variables
