http:
  middlewares:
    rate-login:
      rateLimit:
        average: 5
        burst: 10

    rate-ocr:
      rateLimit:
        average: 10
        burst: 20

    ocr-buffer:
      buffering:
        maxRequestBodyBytes: 10485760  # 10 MB max request size
        memRequestBodyBytes: 2097152   # 2 MB buffer in memory
        maxResponseBodyBytes: 10485760
        memResponseBodyBytes: 1048576
        retryExpression: "IsNetworkError() && Attempts() <= 2"

    ocr-security:
      headers:
        contentSecurityPolicy: "default-src 'none';"
        referrerPolicy: "no-referrer"
        contentTypeNosniff: true
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src 'self'"
        permissionsPolicy: "camera=(), geolocation=()"

  routers:
    odoo-longpolling:
      rule: "Host(`insightpulseai.net`) && (PathPrefix(`/longpolling`) || PathPrefix(`/websocket`))"
      service: odoo-longpolling
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 100

  services:
    odoo-longpolling:
      loadBalancer:
        servers:
          - url: "http://odoo:8072"

# Note: Main Odoo router in compose.yaml Docker labels
# Traefik file provider does not expand environment variables
