http:
  middlewares:
    rate-login:
      rateLimit:
        average: 5
        burst: 10

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src 'self'"
        permissionsPolicy: "camera=(), geolocation=()"

  routers:
    odoo-longpolling:
      rule: "Host(`insightpulseai.net`) && PathPrefix(`/longpolling`)"
      service: odoo-longpolling
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    odoo-longpolling:
      loadBalancer:
        servers:
          - url: "http://odoo:8072"

# Note: Main Odoo router in compose.yaml Docker labels
# Traefik file provider does not expand environment variables
