name: Deploy Odoo 18.0 to DigitalOcean

on:
  workflow_dispatch: {}
  push:
    tags: ['v*.*.*']    # deploy only on version tags
    paths:
      - 'infra/odoo/**'
      - 'scripts/install-modules.sh'
      - '.github/workflows/deploy-odoo.yml'

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: odoo18-oca

jobs:
  deploy:
    if: ${{ secrets.SSH_KEY && secrets.DO_ACCESS_TOKEN }}   # skip if missing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Check OCR health (must pass)
        run: curl -fsS https://ocr.insightpulseai.net/health | jq .

      - name: Skip Odoo deploy if not configured yet
        if: ${{ !secrets.ODOO_IP }}
        run: echo "ODOO_IP not set; skipping deploy step."

      - name: Deploy Odoo (when ready)
        if: ${{ secrets.ODOO_IP }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ODOO_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/odoo && docker compose pull && docker compose up -d

      - name: Odoo health (non-blocking until live)
        if: ${{ secrets.ODOO_FQDN }}
        continue-on-error: true
        run: curl -fsS https://$ODOO_FQDN/web/login || echo "Odoo not live yet (allowed)."
        env:
          ODOO_FQDN: ${{ secrets.ODOO_FQDN }}

