name: Docs / Spec Compile (Deterministic)
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'scripts/spec_compile.sh'
      - '.editorconfig'
      - '.gitattributes'
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'scripts/spec_compile.sh'
      - '.editorconfig'
      - '.gitattributes'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Compile specs (deterministic)
        run: ./scripts/spec_compile.sh docs/specs build/specs.json
      - name: Verify build is committed (no drift)
        run: |
          if ! git diff --quiet -- build/specs.json; then
            echo "::error ::Re-run compile and commit build/specs.json"
            git --no-pager diff -- build/specs.json | tail -n +1
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: specs-bundle
          path: build/specs.json
