name: PR Review • odoobo-expert
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Review PR with odoobo-expert
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          ODOOBO_AGENT_URL: ${{ secrets.ODOOBO_AGENT_URL }}
          ODOOBO_AGENT_KEY: ${{ secrets.ODOOBO_AGENT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/odoobo-reviewer.js
