name: Setup Odoo Production

on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Database name'
        required: true
        default: 'insightpulse_prod'
      admin_email:
        description: 'Admin email'
        required: true
        default: 'jgtolentino_rn@yahoo.com'

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/claude/deployment-setup-011CUK7RaosfewYHhb1QqCUf'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        if: secrets.SSH_KEY && secrets.ODOO_IP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ODOO_IP }} >> ~/.ssh/known_hosts

      - name: Run Odoo Setup via SSH
        if: secrets.SSH_KEY && secrets.ODOO_IP
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.ODOO_IP }} << 'REMOTE_SCRIPT'
          set -e

          CONTAINER="odoo18"
          DB_NAME="${{ github.event.inputs.database }}"
          ADMIN_EMAIL="${{ github.event.inputs.admin_email }}"

          echo "🚀 COMPLETE ODOO SETUP ON PRODUCTION..."
          echo "Database: $DB_NAME"
          echo "Admin: $ADMIN_EMAIL"
          echo ""

          # Install all core Odoo apps
          echo "📦 Installing all Odoo apps..."
          docker exec -i $CONTAINER odoo -d $DB_NAME \
            -i base,web,project,mail,hr,hr_expense,crm,sale,sale_management,purchase,stock,account,calendar,contacts,website,knowledge,documents \
            --without-demo=all \
            --stop-after-init || echo "Apps already installed"

          echo ""

          # Run setup via Odoo shell
          docker exec -i $CONTAINER odoo shell -d $DB_NAME <<'PYEOF'
          env = env.sudo()

          print("🚀 STARTING COMPLETE ODOO SETUP...")
          print("")

          # 1. Create/Update Admin User
          print("👤 Setting up admin user...")
          user = env['res.users'].search([
              '|',
              ('login', '=', 'jgtolentino_rn@yahoo.com'),
              ('login', '=', 'jgtolentino.rn@gmail.com')
          ], limit=1)

          if not user:
              user = env['res.users'].create({
                  'name': 'Admin',
                  'login': 'jgtolentino_rn@yahoo.com',
                  'email': 'jgtolentino_rn@yahoo.com',
                  'password': 'admin123',
              })
              print(f"✅ User created (ID: {user.id})")
          else:
              user.password = 'admin123'
              print(f"✅ User updated (ID: {user.id})")

          # Grant admin rights
          admin_group = env.ref('base.group_system')
          if admin_group.id not in user.groups_id.ids:
              user.groups_id = [(4, admin_group.id)]
          print("✅ Admin rights granted")

          # 2. Create CI/CD Pipeline Project
          print("\n📊 Creating CI/CD Pipeline project...")
          proj = env['project.project'].search([('name', '=', 'CI/CD Pipeline')], limit=1)
          if not proj:
              proj = env['project.project'].create({
                  'name': 'CI/CD Pipeline',
                  'privacy_visibility': 'followers',
              })
              print(f"✅ Project created (ID: {proj.id})")
          else:
              print(f"✅ Project exists (ID: {proj.id})")

          # 3. Create Stages
          print("\n📋 Creating stages...")
          stages = ['Backlog', 'Spec Review', 'In PR', 'CI Green', 'Staging ✅', 'Ready for Prod', 'Deployed', 'Blocked']
          for s in stages:
              if not env['project.task.type'].search([('name', '=', s), ('project_ids', 'in', proj.id)], limit=1):
                  env['project.task.type'].create({'name': s, 'project_ids': [(4, proj.id)]})
                  print(f"  ✅ {s}")

          # 4. Add Custom Fields
          print("\n🔧 Adding custom fields...")
          IrModelFields = env['ir.model.fields']
          task_model_id = env['ir.model']._get_id('project.task')

          def add_field(name, desc, ftype, **kwargs):
              if not IrModelFields.search([('model', '=', 'project.task'), ('name', '=', name)], limit=1):
                  vals = {'name': name, 'model_id': task_model_id, 'field_description': desc, 'ttype': ftype, 'store': True}
                  vals.update(kwargs)
                  IrModelFields.create(vals)
                  print(f"  ✅ {name}")

          add_field('x_pr_number', 'PR Number', 'integer')
          add_field('x_pr_url', 'PR URL', 'char', size=512)
          add_field('x_repo', 'Repository', 'char', size=256)
          add_field('x_commit_sha', 'Commit SHA', 'char', size=64)
          add_field('x_author', 'Author', 'char', size=128)
          add_field('x_deploy_url', 'Deploy URL', 'char', size=512)
          add_field('x_build_status', 'Build Status', 'selection',
                    selection="[('queued','Queued'),('running','Running'),('passed','Passed'),('failed','Failed')]")
          add_field('x_env', 'Environment', 'selection',
                    selection="[('preview','Preview'),('staging','Staging'),('prod','Production')]")
          add_field('x_agent_notes', 'Agent Notes', 'text')

          # 5. Create Discuss Channel
          print("\n💬 Creating #ci-updates channel...")
          channel = env['discuss.channel'].search([('name', '=', 'ci-updates')], limit=1)
          if not channel:
              channel = env['discuss.channel'].create({
                  'name': 'ci-updates',
                  'channel_type': 'channel',
                  'description': 'CI/CD notifications (Your Own Slack)',
              })
              channel.message_post(
                  body="<p>🤖 SuperClaude CI/CD System Ready</p>",
                  message_type='comment',
              )
              print(f"✅ Channel created (ID: {channel.id})")
          else:
              print(f"✅ Channel exists (ID: {channel.id})")

          env.cr.commit()

          print("\n" + "="*60)
          print("✅ SETUP COMPLETE!")
          print("="*60)
          print("\n🔑 Login at: https://insightpulseai.net")
          print("   Email:    jgtolentino_rn@yahoo.com")
          print("   Password: admin123")
          print("\n📊 Created:")
          print("   ✅ Admin user with full access")
          print("   ✅ CI/CD Pipeline project (8 stages)")
          print("   ✅ 9 custom fields")
          print("   ✅ #ci-updates channel")
          print("="*60)
          PYEOF

          echo ""
          echo "✅ Odoo setup completed successfully"
          REMOTE_SCRIPT

      - name: Setup Summary
        run: |
          echo "## ✅ Odoo Setup Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Database:** ${{ github.event.inputs.database }}" >> $GITHUB_STEP_SUMMARY
          echo "**Admin Email:** ${{ github.event.inputs.admin_email }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### What was created:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Admin user with full rights" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ CI/CD Pipeline project" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ 8 stages (Backlog → Deployed)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ 9 custom fields" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ #ci-updates Discuss channel" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Login:" >> $GITHUB_STEP_SUMMARY
          echo "- **URL:** https://insightpulseai.net" >> $GITHUB_STEP_SUMMARY
          echo "- **Email:** jgtolentino_rn@yahoo.com" >> $GITHUB_STEP_SUMMARY
          echo "- **Password:** admin123" >> $GITHUB_STEP_SUMMARY
